const motivationalPhrases = [
  "The best way to get started is to quit talking and begin doing.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don’t wait. The time will never be just right.",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Don’t wish for it. Work for it.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The future depends on what you do today.",
  "You are never too old to set another goal or to dream a new dream.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don’t happen, you create them.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Act as if what you do makes a difference. It does.",
  "If you want to achieve greatness stop asking for permission.",
  "The way to get started is to quit talking and begin doing.",
  "Success is the progressive realization of a worthy goal or ideal.",
  "Don’t limit your challenges. Challenge your limits.",
  "The only place where success comes before work is in the dictionary.",
  "If you can dream it, you can do it.",
  "It always seems impossible until it’s done.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "If you don’t build your dream, someone will hire you to help build theirs.",
  "Don’t count the days. Make the days count.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "The difference between who you are and who you want to be is what you do.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Start where you are. Use what you have. Do what you can.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The secret of getting ahead is getting started.",
  "The harder you work, the luckier you get.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "A goal without a plan is just a wish.",
  "Start where you are. Use what you have. Do what you can.",
];

export const RandomMotiv = () =>
  motivationalPhrases[Math.floor(Math.random() * motivationalPhrases.length)];
